MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Models/CustomHtmlHelpers/HomeWithArrayModel.cs
namespace WorkWithHtmlHelpers.Models.CustomHtmlHelpers
{
	public class ArrayModel
	{
		public string[] Values { get; set; }
	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Models/Editor/EditorForModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WorkWithHtmlHelpers.Models.Editor
{
	public class EditorForModel
	{
		[DataType(DataType.EmailAddress)]
		public string StringField { get; set; }
		[DataType(DataType.Password)]
		public string PasswordField { get; set; }
		public int NumericField { get; set; }
		[AdditionalMetadata("foo", "bar")]
		public DateTime DateTime { get; set; }

		[UIHint("String2")]
		public string StringField2 { get; set; }
	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Models/StandartHtmlHelpers/StrongDataModel.cs
using System.ComponentModel.DataAnnotations;

namespace WorkWithHtmlHelpers.Models.StandartHtmlHelpers
{
	public class StrongDataModel
	{
		public bool IsApproved { get; set; }
		public string SomeProperty { get; set; }
		public string RadioVal { get; set; }
		[DataType(DataType.Password)]
		public string Password { get; set; }
		public string Bio { get; set; }
		public string Name { get; set; }
		public string Gender { get; set; }
		public string[] Vals { get; set; }
	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Controllers/CustomHtmlHelpersController.cs
using System.Web.Mvc;
using WorkWithHtmlHelpers.Models.CustomHtmlHelpers;

namespace WorkWithHtmlHelpers.Controllers
{
	public class CustomHtmlHelpersController : Controller
	{
		public ActionResult InlineHtmlHelper1()
		{
			ArrayModel model = new ArrayModel
			{
				Values = new []{"1", "2", "3"}
			};

			return View(model);
		}

		public ActionResult InlineHtmlHelper2()
		{
			ArrayModel model = new ArrayModel
			{
				Values = new[]{ "1", "2", "3" }
			};

			return View(model);
		}

		public ActionResult ExternalHtmlHelper1()
		{
			ArrayModel model = new ArrayModel
			{
				Values = new[] { "1", "2", "3" }
			};

			return View(model);
		}

		public ActionResult ExternalHtmlHelper2()
		{
			ArrayModel model = new ArrayModel
			{
				Values = new[] { "1", "2", "3" }
			};

			return View(model);
		}
	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Controllers/EditorController.cs
using System;
using System.Web.Mvc;
using WorkWithHtmlHelpers.Models.Editor;

namespace WorkWithHtmlHelpers.Controllers
{
	public class EditorController : Controller
	{
		public ActionResult EditorFor()
		{
			EditorForModel model = new EditorForModel
			{
				DateTime = DateTime.UtcNow,
				NumericField = 10,
				PasswordField = "Password",
				StringField = "String"
			};

			return View(model);
		}

		public ActionResult EditorForModel()
		{
			EditorForModel model = new EditorForModel
			{
				DateTime = DateTime.UtcNow,
				NumericField = 10,
				PasswordField = "Password",
				StringField = "String"
			};

			return View(model);
		}

	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Controllers/HomeController.cs
using System.Web.Mvc;


namespace WorkWithHtmlHelpers.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Controllers/LinkController.cs
using System.Web.Mvc;

namespace WorkWithHtmlHelpers.Controllers
{
	public class LinkController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Controllers/StandartHtmlHelpersController.cs
using System.Web.Mvc;
using WorkWithHtmlHelpers.Models.StandartHtmlHelpers;

namespace WorkWithHtmlHelpers.Controllers
{
	public class StandartHtmlHelpersController : Controller
	{
		public ActionResult CreateForm()
		{
			return View();
		}

		public ActionResult PostForm()
		{
			return RedirectToAction("CreateForm");
		}

		public ActionResult DataInput()
		{
			return View();
		}

		public ActionResult StrongDataInput()
		{
			return View(new StrongDataModel
			{
				IsApproved = true,
				SomeProperty = "SomeProperty",
				RadioVal = "val",
				Password = "Password",
				Bio = "Bio",
				Name = "Name",
				Gender = "F",
				Vals = new []{"A"}
			});
		}

		public ActionResult StrongDataInputWithAttributes()
		{
			return View(new StrongDataModel
			{
				IsApproved = true,
				SomeProperty = "SomeProperty",
				RadioVal = "val",
				Password = "Password",
				Bio = "Bio",
				Name = "Name",
				Gender = "F",
				Vals = new[] { "A" }
			});
		}
	}
}

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Views/CustomHtmlHelpers/ExternalHtmlHelper1.cshtml
@using WorkWithHtmlHelpers.Helpers.HtmlHelpers
@model WorkWithHtmlHelpers.Models.CustomHtmlHelpers.ArrayModel

<!DOCTYPE html>

<html>
	<head>
		<title>External Html Helper</title>
	</head>
	<body>
		<div>
			@Html.ListArrayitems(Model.Values)
		</div>
	</body>
</html>

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Views/CustomHtmlHelpers/ExternalHtmlHelper2.cshtml
@model WorkWithHtmlHelpers.Models.CustomHtmlHelpers.ArrayModel

<!DOCTYPE html>

<html>
	<head>
		<title>Declarative Html Helper</title>
	</head>
	<body>
		<div>
			@CustomHelpers.ListArrayItems(Model.Values)
		</div>
	</body>
</html>

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Views/CustomHtmlHelpers/InlineHtmlHelper1.cshtml
@model WorkWithHtmlHelpers.Models.CustomHtmlHelpers.ArrayModel

<!DOCTYPE html>

<html>
	<head>
		<title>Before Inline HTML Helpers</title>
	</head>
	<body>
		@foreach (string item in Model.Values)
		{
			<text>@item &nbsp;</text>
		}
	</body>
</html>

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Views/CustomHtmlHelpers/InlineHtmlHelper2.cshtml
@model WorkWithHtmlHelpers.Models.CustomHtmlHelpers.ArrayModel

@helper ListArrayItems(string[] array)
{
	foreach (string item in Model.Values)
	{
		<text>@item &nbsp;</text>
	}
}

<!DOCTYPE html>
<html>
	<head>
		<title>Inline HTML Helpers</title>
	</head>
	<body>
		@ListArrayItems(Model.Values)
	</body>
</html>

MVC-5/Lections-Examples/StudentsLabs.HtmlHelpers/Views/Link/Index.cshtml
@{
	ViewBag.Title = "Links";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="@Url.Content("~/Content/image.jpg")"/><br/>
@Html.ActionLink("ActionLink", "Index", "Link")<br/>
@Html.ActionLink("ActionLink", "Index", "Link", "https", "www.test.com", "anchor", new{}, null)<br/>
<a href="@Url.Action("Index", "Link")">RouteUrl</a><br/>
<a href="@Url.RouteUrl(new { controller = "Link", action = "Index" })">RouteUrl</a><br/>
<a href="@Html.RouteLink("Hi", new { controller = "Link", action = "Index" }, null)">RouteLink</a><br/>
@*@Html.RouteLink("Hi", "myNamedRoute", new {})*@